//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csi3370parksofficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Park
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Park()
        {
            this.Events = new HashSet<Event>();
            this.ParkFacilities = new HashSet<ParkFacility>();
        }
    
        public string ParkName { get; set; }
        public string ParkAddress { get; set; }
        public string ParkCity { get; set; }
        public string ParkCounty { get; set; }
        public Nullable<int> ParkZipCode { get; set; }
        public Nullable<bool> ParkFee { get; set; }
        public string ParkHours { get; set; }
        public Nullable<bool> DogFriendly { get; set; }
        public string ParkPhoneNumber { get; set; }
        public Nullable<int> ParkTypeID { get; set; }
        public string ParkWebsite { get; set; }
        public int ParkID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkFacility> ParkFacilities { get; set; }
        public virtual ParkType ParkType { get; set; }
    }
}
